### ISSUE TITLE
feature - Option to cancel the question request in case user waits for too long

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#117]
Option to cancel the question request in case user waits for too long 
      User Config - 
      1. Rag - true 
      2. Location - false
      3. UserId - f9eaacbf-ef41-4805-b876-2a5b9b73bedd 
      4. Balance - 992523994 
      Detailed Message -

**Comment by rajatsharma29** [comment]
@samyak112  please review
