### ISSUE TITLE
feedback - error message keeps on appearing even after adding the second question to abstract

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#118]
error message keeps on appearing even after adding the second question to abstract. it should disappear automatically once i add the first question. 
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - f9eaacbf-ef41-4805-b876-2a5b9b73bedd 
      4. Balance - 992484959 
      Detailed Message -

**Comment by rajatsharma29** [comment]
@samyak112 please review
