### ISSUE TITLE
bug - 1 contract is failed every time we upload contracts due to OCR contracts contain Images / Add check for this until we work on OCR

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#138]
4/5 , 2/3 each time 1 contract failed 
 
      User Config - 
      1. Rag - false 
      2. Location - false
      3. UserId - 4540ee20-6241-411f-9e81-ca0d9473b14c 
      4. Balance - 86971992 
      Detailed Message - 
       ![Alt Text](https://legalgraphaiprod.blob.core.windows.net/images/6959ed56602d-47ee-b9b2-7f28cb30329e1703332423735Screenshot%20(411).png?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2027-01-01T15:33:17Z&st=2023-09-26T07:33:17Z&spr=https&sig=84Xh2so4BJhpHs9vwiZiBj9DR7TW7AKzOP0oLa98WeI%3D)

**Comment by Habibamunir123** [comment]
Will be fixed when we  OCR pdf release
