### ISSUE TITLE
bug - For new user we are failing too late 

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#142]
Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - 
   
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - 8f65335c-14ea-4ae3-8cd7-6f07cf3bfc89 
      4. Balance - 950927223 
      Detailed Message - 
       ![Alt Text](https://devchatcontractai.blob.core.windows.net/images/55152cb75752-45c6-9242-8ab693f08cc71703519367345Screenshot%202023-12-25%20at%207.47.01%20AM.png?sv=2022-11-02&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2027-09-20T21:46:17Z&st=2023-09-21T13:46:17Z&spr=https&sig=kGLZhYMxGbBpt%2FOzUrJgobp6R%2F3dTPDW9amNbYIkbns%3D)

**Comment by rajatsharma29** [comment]
resolved
