### ISSUE TITLE
bug - Repository Table Bug / Remove Multiple contract / Check boxes

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#144]
When user selected multiple contracts mostly some of them deleted and sometime showing the error

Also when we deleted the selected contract the next contracts also selected automatically 
      User Config - 
      1. Rag - false 
      2. Location - false
      3. UserId - 4540ee20-6241-411f-9e81-ca0d9473b14c 
      4. Balance - 86971992 
      Detailed Message -

**Comment by rajatsharma29** [comment]
resolved
