### ISSUE TITLE
feedback - Not able t o view the page number in the dropdown for edit cell value feature

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#148]
Not able t o view the page number in the dropdown for edit cell value feature 
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - ad34d140-ba11-4bb8-b452-e2cf2776d42c 
      4. Balance - 1004078234 
      Detailed Message -

**Comment by rajatsharma29** [comment]
resolved
