### ISSUE TITLE
feedback - the confidence number inside the cell is confusing

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#151]
the confidence number inside the cell is confusing as user cant tell what does the number represents. we can show an 'i' icon at the top right corner of the cell where on mouse hover/click we can display the info that this is the accuracy value by AI for the result.
 
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - ad34d140-ba11-4bb8-b452-e2cf2776d42c 
      4. Balance - 1003743117 
      Detailed Message -

**Comment by samyak112** [comment]
We did suggested this that we can show the confidence with i button , but mahesh suggested to show confidence in the way it is right now, we can discuss with him if we want to change this @rajatsharma29
