### ISSUE TITLE
bug - Ploblem in uploading and analysis feature

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#158]
When I tried to upload a sample agreement and hit the analyze button,  some error message appeared, and I could not go on to the next page. 
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - 679262a9-bc4d-4e78-8596-bee5fdb2c9ce 
      4. Balance - undefined 
      Detailed Message -

**Comment by Habibamunir123** [comment]
Done
