### ISSUE TITLE
Bug - Master Settings - Do not allow user to add key terms with same name (case sensitive entries as well)

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#177]
Master Settings - Do not allow user to add key terms with same name (case sensitive entries as well) 
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - ad34d140-ba11-4bb8-b452-e2cf2776d42c 
      4. Balance - 19716311 
      Detailed Message -

**Comment by rajatsharma29** [comment]
resolved
