### ISSUE TITLE
bug - Unable to Review and Analyses all the agreements uploaded

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#180]
Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - 
   
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - 564ff922-a438-4b37-88ea-3e8f59e3051c 
      4. Balance - 19826181 
      Detailed Message -

**Comment by rajatsharma29** [comment]
resolved
