### ISSUE TITLE
Bug - Unable to change the question of the key term without changing the text of key name (same for changing key name)

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#181]
Unable to change the question of the key term without changing the text of key name 
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - ad34d140-ba11-4bb8-b452-e2cf2776d42c 
      4. Balance - 16656419 
      Detailed Message -

**Comment by rajatsharma29** [comment]
resolved
