### ISSUE TITLE
bug - After payment of $99, the amount is shown as $9.99 to user in settings

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#183]
After payment of $99, the amount is shown as $9.99 to user in settings 
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - ad34d140-ba11-4bb8-b452-e2cf2776d42c 
      4. Balance - 25225912.5 
      Detailed Message -

**Comment by rajatsharma29** [comment]
resolved
