### ISSUE TITLE
bug - Unable to delete contracts in prod

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#188]
Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - {"type":"cors","url":"https://backend.legalgraph.ai/api/v1/delete-contract","status":200,"statusText":"OK","redirected":false}
   
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - f9eaacbf-ef41-4805-b876-2a5b9b73bedd 
      4. Balance - 926925718 
      Detailed Message - {"type":"cors","url":"https://backend.legalgraph.ai/api/v1/delete-contract","status":200,"statusText":"OK","redirected":false}

**Comment by rajatsharma29** [comment]
resolved
