### ISSUE TITLE
bug - Search does not work if i enter a word present between the document name in search box

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#191]
Search does not work if i enter a word present between the document name in search box
  Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - 
   
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - ad34d140-ba11-4bb8-b452-e2cf2776d42c 
      4. Balance - 19519938.5 
      Detailed Message -

**Comment by rajatsharma29** [comment]
resolved
