### ISSUE TITLE
bug - user data not visible in account settings (User ID not found)

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#195]
Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - {"stack":"TypeError: Failed to fetch\n    at https://legalgraph.ai/assets/index-48535533.js:99:39320\n    at p (https://legalgraph.ai/assets/PageSelector-48f52614.js:96:4687)\n    at https://legalgraph.ai/assets/PageSelector-48f52614.js:96:5159\n    at av (https://legalgraph.ai/assets/index-48535533.js:40:24263)\n    at ou (https://legalgraph.ai/assets/index-48535533.js:40:42315)\n    at SR (https://legalgraph.ai/assets/index-48535533.js:40:41163)\n    at ho (https://legalgraph.ai/assets/index-48535533.js:40:40212)\n    at c1 (https://legalgraph.ai/assets/index-48535533.js:40:36824)\n    at qi (https://legalgraph.ai/assets/index-48535533.js:38:3274)\n    at https://legalgraph.ai/assets/index-48535533.js:40:34207","message":"Failed to fetch"}
   
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - f9eaacbf-ef41-4805-b876-2a5b9b73bedd 
      4. Balance - 926608820.5 
      Detailed Message - {"stack":"TypeError: Failed to fetch\n    at https://legalgraph.ai/assets/index-48535533.js:99:39320\n    at p (https://legalgraph.ai/assets/PageSelector-48f52614.js:96:4687)\n    at https://legalgraph.ai/assets/PageSelector-48f52614.js:96:5159\n    at av (https://legalgraph.ai/assets/index-48535533.js:40:24263)\n    at ou (https://legalgraph.ai/assets/index-48535533.js:40:42315)\n    at SR (https://legalgraph.ai/assets/index-48535533.js:40:41163)\n    at ho (https://legalgraph.ai/assets/index-48535533.js:40:40212)\n    at c1 (https://legalgraph.ai/assets/index-48535533.js:40:36824)\n    at qi (https://legalgraph.ai/assets/index-48535533.js:38:3274)\n    at https://legalgraph.ai/assets/index-48535533.js:40:34207","message":"Failed to fetch"}

**Comment by rajatsharma29** [comment]
resolved
