### ISSUE TITLE
bug - new user test - review does not works - no data found error

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#196]
Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - 
   
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - 9733a05a-6474-4c3f-8358-c4f7fff2d45a 
      4. Balance - 200000 
      Detailed Message -

**Comment by rajatsharma29** [comment]
resolved
