### ISSUE TITLE
bug - not able to proceed after step 3 - analyze button gives error

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#197]
not able to proceed after step 3 - analyze button gives error (rajat)
  Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - {"stack":"SyntaxError: Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON","message":"Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON"}
   
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - f9eaacbf-ef41-4805-b876-2a5b9b73bedd 
      4. Balance - undefined 
      Detailed Message - {"stack":"SyntaxError: Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON","message":"Unexpected token '<', \"<!DOCTYPE \"... is not valid JSON"}

**Comment by rajatsharma29** [comment]
resolved
