### ISSUE TITLE
bug - Key term is unique but showing the duplicacy error 

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#213]
Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - [{"active":true,"category":"Term & termination","key":"end date","question":"what is the end date?","type":"master_service","KeyTermId":"79277952-9c48-46c6-9f54-3d8c941d6cf6"}]
   
      User Config - 
      1. Rag - true 
      2. Location - true
      3. UserId - 8a56df1f-433d-417b-8945-55ca35da8f0f 
      4. Balance - 19247538 
      Detailed Message - [{"active":true,"category":"Term & termination","key":"end date","question":"what is the end date?","type":"master_service","KeyTermId":"79277952-9c48-46c6-9f54-3d8c941d6cf6"}]

**Comment by Mayank-dev1822** [comment]
FIX PR: https://github.com/chatcontract/django-ml-backend/pull/130
