### ISSUE TITLE
PROD - Bug - Error on loading key terms

### ISSUE THREAD

**Issue by rajatsharma29** [chatcontract/public-issues#248]
when i went to settings to view the key terms a error popup appeared with message 

"Whoops! Something went wrong. Please retry by clicking the button below."

refer image attached

![PROD - 30 may - error on loading key terms](https://github.com/chatcontract/public-issues/assets/133215682/e8aa8efe-4faa-4dc7-88c3-f45fda75edee)

**Comment by Mayank-dev1822** [comment]
Sorry, our production was down at the moment and we forgot to add the maintenance screen.
