### ISSUE TITLE
bug - Beta - bug - unable to analyse contracts

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#262]
Beta - Bug - no data error on data table page

all results are not processed. the processing stops in midway

  Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - 
   
      UserId - 3ea53dbb-9bc4-4270-a321-4defc2b16ef8 
      Detailed Message -

**Comment by samyak112** [comment]
Not a bug, you need to change the contract type to see the contracts of that type
