### ISSUE TITLE
Incorrect answer and citation for the Key Term "Suspension" in AWS MSA

### ISSUE THREAD

**Issue by rajatsharma29** [chatcontract/public-issues#302]
Contract Name: AWS Contract.
Key Term: Name Suspension.
Legalgraph's Answer: Section 4.1 >> Incorrect
Correct Answer: Yes
Citation 1 By LegalGraph: Page 3  >> Correct
Citation 2 By LegalGraph: Page 5 >> Incorrect
COT: Relevant

Issues:
Answer by AI is incorrect -- AI gives the answer as "Section 4.1" which does not provide user with any clarity on the Query about the Key Term suspension.
The query is: "Does the Service provider has the right to suspend work if not paid?" and answer should be in Yes or No format.

Citation is not highlighted correctly for citation 1 (page 3)
Citation is not highlighted at all for citation 2 (page 5)

UpLoaded: The Contract and Results spreadsheet with this message.
[Results - AWS Customer Agreement - May 2024.pdf.csv](https://github.com/user-attachments/files/16039802/Results.-.AWS.Customer.Agreement.-.May.2024.pdf.csv)

[AWS Customer Agreement - May 2024.pdf](https://github.com/user-attachments/files/16039799/AWS.Customer.Agreement.-.May.2024.pdf)

**Comment by samyak112** [comment]
### RCA 
This happened because the question associated with this key term is not clear and is not clearly making sense as what is needed as the answer, here is the question - "Right to suspend work if not paid"

**Comment by samyak112** [comment]
### Solution
Changed the question to - "Does the Service provider has the right to suspend work if not paid?"

![image](https://github.com/chatcontract/public-issues/assets/73217093/ca8f0e67-a4cf-425d-8db0-be76580766ee)
![image](https://github.com/chatcontract/public-issues/assets/73217093/ad71e258-8221-43fd-bd15-286f3daab263)
