### ISSUE TITLE
Payment due date value incorrect by AI on AWS Contract

### ISSUE THREAD

**Issue by rajatsharma29** [chatcontract/public-issues#304]
In AWS Contract the payment Due Date is not mentioned but the AI Gives the values as "monthly"

AI Answer: Monthly
Correct Answer: Not Mentioned in Agreement

AI Citation: 2,4
Correct Citation: N/A

Key Term name: Payment Due Date
Question: When is payment due? (answer needed about the date as the name is due date)

Contract link: https://drive.google.com/file/d/1XAZ17NXnOyOP-xeKnbO0KenpNriULOa0/view?usp=drive_link
Re
[Results - AWS Customer Agreement - May 2024.pdf.csv](https://github.com/user-attachments/files/16040169/Results.-.AWS.Customer.Agreement.-.May.2024.pdf.csv)
sults: Attached

**Comment by samyak112** [comment]
### RCA
This happened because the question was not clear it states - "When is payment due?" it does not clears how we want the answer as

**Comment by samyak112** [comment]
### Solution
I changed the question to 'What is the date of Payment Due" and here are the results - 
![image](https://github.com/chatcontract/public-issues/assets/73217093/2b5a6931-ab17-4bb6-b3e7-7b0cd946164a)

![image](https://github.com/chatcontract/public-issues/assets/73217093/6f7f7fbb-6d2f-48fa-ae4c-aa91f2561e2d)
