### ISSUE TITLE
Unable to find value for Key Term "Price Increase" in AWS Contract

### ISSUE THREAD

**Issue by rajatsharma29** [chatcontract/public-issues#305]
LegalGraph AI Answer: Not Found
Correct Answer: Yes

LegalGraph Citation: N/A
Correct Citation: Section 3, Page 2

Key Term Name: Price Increase
Question: Does the agreement include a provision for increasing the price of the services? Please provide a yes or no answer if possible.

Contract link: https://drive.google.com/file/d/1XAZ17NXnOyOP-xeKnbO0KenpNriULOa0/view?usp=drive_link
Results: Attached
[Results - AWS Customer Agreement - May 2024.pdf.csv](https://github.com/user-attachments/files/16040186/Results.-.AWS.Customer.Agreement.-.May.2024.pdf.csv)

**Comment by samyak112** [comment]
### RCA
Final relevant chunks did not had any information regarding the Price increase, thats why the answer was wrong
