### ISSUE TITLE
bug - Prod - Unable to analyze contract

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#314]
when i select the Viant Corp contract from repository for analysis i get an error on the data table page.

  Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - Some Files failed to load
   
      UserId - f9eaacbf-ef41-4805-b876-2a5b9b73bedd 
      Detailed Message - Some Files failed to load

**Comment by Mayank-dev1822** [comment]
RCA: As we are also using this VM for all the deployments for app associates and also to access their VM, I installed a remote desktop client on the VM's system called XRDP remote desktop, using this we were able to access the VM using the remote desktop connection and test out their builds. 

FIX: This XRDP server was not stable, this instability was causing our GPU drivers and docker service to crash. I have disabled the XRDP server running on the VM completely and I have also shut down any other dependent RDP-related services.
