### ISSUE TITLE
bug - Beta - Unable to analyze contracts and view key terms info

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#315]
Beta - Unable to analyze contracts and view key terms info

  Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - 
   
      UserId - 3ea53dbb-9bc4-4270-a321-4defc2b16ef8 
      Detailed Message -

**Comment by Mayank-dev1822** [comment]
RCA: As we are also using this VM for all the deployments for app associates and also to access their VM, I installed a remote desktop client on the VM's system called XRDP remote desktop, using this we were able to access the VM using the remote desktop connection and test out their builds.

FIX: This XRDP server was not stable, this instability was causing our GPU drivers and docker service to crash. I have disabled the XRDP server running on the VM completely and I have also shut down any other dependent RDP-related services.
