### ISSUE TITLE
bug - prod - new contracts not able to process files

### ISSUE THREAD

**Issue by ChatContractAI** [chatcontract/public-issues#326]
Description - [What went wrong? Keep it brief.]
  Steps to Reproduce - [How can we make this bug happen?]
  Expected Behavior - [What did you expect to see?]
  Actual Behavior - [What did you actually see?]
  Error - 
  

Steps to replicate:
go to upload
add new contracts
analyze

on data table page: No data found error 
      UserId - f9eaacbf-ef41-4805-b876-2a5b9b73bedd 
      Detailed Message -

**Comment by Mayank-dev1822** [comment]
## FIXED: Reverted back to the older version of production build
![image](https://github.com/user-attachments/assets/c84f8879-df2d-40a6-b390-ef1b526839db)
